#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE: Dealing with PDFs | UC Linux Wiki
#+OPTIONS: num:nil
#+EXPORT_FILE_NAME: ../dealing-with-pdfs.html

PDF are the most widely used file formats in this era for most things digital that needs some formatting. And as a student you have to submit a lot of things in pdf, or get things in pdf.

Here are details on few tools, and tips on making that easier. The first part talks about the things we can do with pdfs and a non exhaustive list of softwares that can do it, and then the second part describes individual software packages with their functions.

* Creating PDFs
Almost all the content manipulation/creation softwares has a export to pdf function nowadays so there is no limit to what could be put into this section. Let's just focus on few softwares that might be the top ones in the FOSS market.
** [[https://www.latex-project.org/][LaTeX]]
For creation of well formatted PDFs for thesis, homeworks, notes, reports, and such. Since LaTeX is a gient in itself, we'll soon develop a different page for it with more details on it.

The package [[https://ctan.org/pkg/pdfoverlay][pdfoverlay]] can put pdf pages in the background so you can add texts on it.

** [[https://inkscape.org/][Inkscape]]
For making any diagrams in the PDF format, this is the perfect tool. Making svgs, or pdfs with vector graphics means having high quality graphics in your documents. You can insert the svg or pdf into your LaTeX document with ease.

** [[https://github.com/xournalpp/xournalpp][Xournal++]]
For making pdfs with handwritten notes. Xournal++ is a program that gives you pages to take notes, you can have handwritten notes, sketches and such without the complexity of graphics manipulator program like Inkscape. You can export the notes to PDF and include it into your homeworks or reports, or just have standalone PDF.

* Conversion between raster Image and PDFs
** [[https://imagemagick.org/][imagemagick]]
If you just want to convert image into pdf, without actually making the contents like previous ones. You can use this. All you need is a single command =convert input.png output.pdf= and it'll do the conversion for you. It's useful when you need to submit pdfs and you have image. No need to insert the image into a word processor and export to pdf ever again.

And it can also do the reverse, i.e. convert a pdf into image. Make sure to give a suitable dpi parameter, and you'll get a image for each page of the pdf. There is also =pdftoppm= command that does it (I think).
** [[https://github.com/tesseract-ocr/tesseract][tesseract]]
And if you want to convert image to searchable pdfs. Like with images of some text (book, or reports), then you can use tesseract. It can make searchable pdfs for you. I wish it could use pdf as input and give pdf output by processing the embedded images in the pdf, but it can only take image inputs.

* Manipulating PDF pages
** [[https://en.wikipedia.org/wiki/Poppler_(software)#poppler-utils][poppler-utils]]
It can merge pdfs with a simple commad =pdfunite=, get text from pdfs, get embedded images from pdf, and many more.

* Editing PDF Contents
Even though PDFs are supposed to be the final stage before printing, meaning they are only supposed to be converted to image format, or formats for the printers to understand. We do have moments when we want to modify the contents.

PDF is a binary file format, which means you cannot directly open it in a text editor and edit it (or can you?). But some softwares give you specific ways to edit it.

** [[https://inkscape.org/][Inkscape]]
You can open pdf files in inkscape and it'll load it as vector graphics. You can make your edit and re export them. Or you can extract the vector graphics inside some pages and save it.

** [[https://qpdf.readthedocs.io/en/stable/index.html][qpdf]]
qpdf has [[https://qpdf.readthedocs.io/en/stable/qdf.html][qdf mode]], which is a completely valid pdf, that is made to be editable with a simple text editor as much as possible. And since it's a valid pdf, you can just edit it and open it with any pdf viewing software.

You can edit the contents and move around pages, or remove/add them (to some extent) when your're dealing with qdf with just any editor you like. But be careful to not mess up the pdf structure.

* Filling PDFs
This is a little different than simple editing in that the previous contents of the PDF will be same, and you'll just add overlays, it's nice for adding notes, or filling/signing forms.

** [[https://github.com/xournalpp/xournalpp][Xournal++]]
For making pdfs with handwritten notes. Xournal++ is a program that gives you pages to take notes, you can have handwritten notes, sketches and such without the complexity of graphics manipulator program like Inkscape. You can export the notes to PDF and include it into your homeworks or reports, or just have standalone PDF.

** [[https://www.latex-project.org/][LaTeX]]
The package [[https://ctan.org/pkg/pdfoverlay][pdfoverlay]] can put pdf pages in the background so you can add texts on it. This is useful when you want to use multiple inputs to fill multiple forms in a batch process. Or if you need to repeate it.

* Viewing PDFs
This seems straightforward, but there are ways to view pdfs (like presentation mode). There are a lot of FOSS programs for viewing pdfs, so I'm currently only listing the ones I use often.

** [[https://launchpad.net/qpdfview][qpdfview]]
simple and minimalistic pdf view.

** [[https://pdfpc.github.io/][pdfpc]]
This is an excellent program to present slides from pdf. It is most useful for slides made with LaTeX beamer, as it has support for multi monitor setup, frame animations, gifs, videos, timer, pointer, sketch, and many more features you might need while presenting.

** [[https://www.gnu.org/software/emacs/][Emacs]]
Emacs can view pdfs with extentions. Not only that, it can have extensions to make notes related to the pdf file, with postitioning saved. It can make/browse table of contents. It can use synctex to locate the source position from pdf generated with LaTeX. It can probably do a lot more as users of emacs are familiar with it.

